parameters:
    kunstmaan_extra.public_node_versions.class: 'ArsThanea\KunstmaanExtraBundle\SiteTree\PublicNodeVersions'
    kunstmaan_extra.content_category.class: 'ArsThanea\KunstmaanExtraBundle\ContentCategory\ContentCategoryService'
    kunstmaan_extra.site_tree.current_locale.class: 'ArsThanea\KunstmaanExtraBundle\SiteTree\CurrentLocale'
    kunstmaan_extra.site_tree.bread_crumbs.class: 'ArsThanea\KunstmaanExtraBundle\SiteTree\BreadCrumbsService'
    kunstmaan_extra.navigation.navigation.class: 'ArsThanea\KunstmaanExtraBundle\SiteTree\Navigation\Navigation'
    kunstmaan_extra.content_type.class: 'ArsThanea\KunstmaanExtraBundle\ContentType\ContentTypeService'
    kunstmaan_extra.site_tree.class: 'ArsThanea\KunstmaanExtraBundle\SiteTree\SiteTreeService'
    kunstmaan_extra.page_url.class: 'ArsThanea\KunstmaanExtraBundle\Url\PageUrlService'
    kunstmaan_extra.intl.date_formatter.class: 'ArsThanea\KunstmaanExtraBundle\Intl\DateFormatter'
    kunstmaan_extra.page_context.page_controller_context.class: 'ArsThanea\KunstmaanExtraBundle\Page\PageContext\PageControllerContext'
    kunstmaan_extra.wysiwyg_filter.class: 'ArsThanea\KunstmaanExtraBundle\WysiwygFilter\WysiwygFilter'

services:
    kunstmaan_extra.public_node_versions:
        class: '%kunstmaan_extra.public_node_versions.class%'
        arguments: [ '@doctrine.orm.entity_manager', '@kunstmaan_extra.site_tree.current_locale' ]

    kunstmaan_extra.content_category:
        class: '%kunstmaan_extra.content_category.class%'
        arguments:
          - '@doctrine_cache.providers.kunstmaan_extra_content_category'
          - '@kunstmaan_extra.public_node_versions'
          - '@kunstmaan_extra.site_tree.bread_crumbs'

    kunstmaan_extra.site_tree.current_locale:
        class: '%kunstmaan_extra.site_tree.current_locale.class%'
        arguments: [ '@request_stack', '@kunstmaan_admin.domain_configuration' ]

    kunstmaan_extra.site_tree.bread_crumbs:
        class: '%kunstmaan_extra.site_tree.bread_crumbs.class%'
        arguments: [ '@ars_thanea_kunstmaan_extra.node_repository', '@kunstmaan_extra.site_tree.current_locale' ]


    kunstmaan_extra.content_type:
        class: '%kunstmaan_extra.content_type.class%'
        arguments: [ '@kunstmaan_node.pages_configuration' ]


    kunstmaan_extra.site_tree:
        class: '%kunstmaan_extra.site_tree.class%'
        arguments:
          - '@ars_thanea_kunstmaan_extra.node_repository'
          - '@kunstmaan_extra.public_node_versions'
          - '@kunstmaan_extra.site_tree.current_locale'

    kunstmaan_extra.site_tree.branch_utilities_service:
        class: 'ArsThanea\KunstmaanExtraBundle\SiteTree\BranchUtilitiesService'

    kunstmaan_extra.navigation.navigation:
        class: '%kunstmaan_extra.navigation.navigation.class%'
        arguments:
          - '@kunstmaan_extra.site_tree'
          - '@kunstmaan_extra.content_category'
          - '@kunstmaan_extra.site_tree.branch_utilities_service'

    kunstmaan_extra.page_url:
        class: '%kunstmaan_extra.page_url.class%'
        arguments: [ '@kunstmaan_extra.public_node_versions', '@router' ]

    ars_thanea_kunstmaan_extra.request_param_converter.page_param_converter:
        public: false
        class: 'ArsThanea\KunstmaanExtraBundle\Request\ParamConverter\PageParamConverter'
        arguments: [ '@doctrine', '@kunstmaan_extra.content_type' ]
        tags:
            - { name: request.param_converter, converter: "kunstmaan_extra.page" }

    ars_thanea_kunstmaan_extra.node_repository:
        public: false
        class: 'Kunstmaan\NodeBundle\Repository\NodeRepository'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: [ 'KunstmaanNodeBundle:Node' ]

    ars_thanea_kunstmaan_extra.node_translation_repository:
        public: false
        class: 'Kunstmaan\NodeBundle\Repository\NodeTranslationRepository'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: [ 'KunstmaanNodeBundle:NodeTranslation' ]

    kunstmaan_extra.intl.date_formatter:
        class: '%kunstmaan_extra.intl.date_formatter.class%'
        public: false
        arguments: [ '@kunstmaan_extra.site_tree.current_locale', '%kunstmaan_extra.date_formats%' ]


    kunstamaan_extra.page_context:
      class: 'ArsThanea\KunstmaanExtraBundle\Page\PageContext\PageContext'
      arguments: [ '@kunstamaan_extra.page_context.collection' ]
      tags:
        - name: nassau.registry
          tag: page_context_provider
          method: ~
          use_collection: true
          order: priority
          class: 'ArsThanea\KunstmaanExtraBundle\Page\PageContext\PageContextProviderInterface'


    kunstmaan_extra.page_context.page_controller_context:
        class: '%kunstmaan_extra.page_context.page_controller_context.class%'
        public: false
        arguments: [ '@service_container' ]
        tags:
          - name: page_context_provider
            priority: 0

    kunstmaan_extra.wysiwyg_filter:
        class: '%kunstmaan_extra.wysiwyg_filter.class%'
        arguments:
          - '@kunstmaan_extra.wysiwyg_filter.crawler'
          - '%kunstmaan_extra.bem%'

    kunstmaan_extra.wysiwyg_filter.crawler:
        class: 'Symfony\Component\DomCrawler\Crawler'
        public: false

    ars_thanea_kunstmaan_extra.imagine.srcset_calculator:
        class: 'ArsThanea\KunstmaanExtraBundle\Imagine\SrcsetCalculator'
        public: false
        arguments:
          - '@liip_imagine.cache.manager'
          - '%kunstmaan_extra.srcset_breakpoints%'
          - image_width_threshold: '%kunstmaan_extra.srcset_image_width_threshold%'
            default_filter: '%kunstmaan_extra.srcset_default_filter%'
        calls:
          - [ 'setResizer', [ '@?ars_thanea.kunstmaan_extra.imagine.imgix_filter' ] ]
